### ISSUE TITLE
Bot stopping ongoing sessions randomly 

### ISSUE THREAD

**Issue by agent4tea7** [MarcoPereira27/pomodore-discord-bot#5]
![B44FF570-6613-4C9E-AF79-0516197330A8](https://user-images.githubusercontent.com/76402202/104133617-a2f5cd00-537c-11eb-8134-8c22eba08fd5.jpeg)
![A28EFE45-60CA-4C4D-AE65-F442B0274BDF](https://user-images.githubusercontent.com/76402202/104133618-a4bf9080-537c-11eb-89c4-77c73c6108e7.jpeg)

As seen in images - bot was in session, at 17.21. A few minutes later there it was, not in the session. No pd!stop was issues between the two time points

**Comment by MarcoPereira27** [comment]
Hello! 
This is happening due to some kind of memory leak I described in issue #4, I'm currently working on a fix!
