### ISSUE TITLE
Setting number of pomodoros between big breaks

### ISSUE THREAD

**Issue by friederikemeier** [MarcoPereira27/pomodore-discord-bot#8]
Hey!
I would like to add the functionality to set the number of pomodoros between big breaks.
I think it should just be a fourth optional argument to `pd!start`, so if I enter
`pd!start 25 5 15 5` it lets me do 5 pomodoros instead of the default 4. 

What do you think?

**Comment by MarcoPereira27** [comment]
Hello!
Love the idea, feel free to start working on it!
If you ever need any help, please join the [Pomodore Support Server](https://discord.com/invite/UqrA9nusjd) and I'll be happy to help with whatever you need!

**Comment by friederikemeier** [comment]
Not working on this anymore as well.
